<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Unidad</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>088a8a47-b44d-4f61-878d-f20b6b5ad876</testSuiteGuid>
   <testCaseLink>
      <guid>09a273ba-9a6f-4731-9d50-e5f9db52dc94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Catalogos/Unidades/Unidad minera/Create_unit</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c73b64f6-cbfd-47d2-a665-ef0590800a7a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Catalogos/Unidades mineras</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f1d973a-8a31-44ea-a483-0b40eae015e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>842f96bc-ed00-4673-9d0a-5865a29de5e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3fd87d1-d050-4308-8974-84a7f22fe72e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e2cbe18-e3d3-43de-bf2c-a6ec1359070e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1eb504b8-d4ba-4e80-a1c2-f0e0d614b0e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Catalogos/Unidades/Unidad minera/Verify_unit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>446512cb-9c42-415f-b99a-72194d310043</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a48ca46d-6aa1-4591-9155-9cec36be44ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba9b0b9f-dfc7-44fc-a313-49766e8e4463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e13cd3f0-0e5f-4109-b609-46a721172012</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>89d3553f-787d-4759-a9eb-4bd1a1e5e697</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Catalogos/Unidades/Capacidades mineras/Create_capacity</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>387eede1-dd47-4414-817d-1e43a6530db7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf9403a0-4564-4bd5-87f8-7a0c207d8e35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bff2eb72-59ee-4339-a5d2-917471f0c129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94b89f16-aa34-4b09-8610-733bdc20f0d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e594136-d324-463a-b58d-69a1eac35142</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Catalogos/Unidades/Capacidades mineras/Verify_capacity</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94d0b15b-bc4c-4768-beed-19378972e32d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdec69b1-34d3-4fb2-91ea-5563e375e0ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46d61667-e3b5-44a3-a37b-cb81d3ac6ff3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78723868-e9f2-44af-92bb-3f4462f397c3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
